POST http://localhost:8000/api/courses
Content-Type: application/json

{
    "name": "Probability",
    "code": "MT1021",
    "content": "abcd"
}

###

GET http://localhost:8000/api/users

###

PUT http://localhost:8000/api/users/40
Content-Type: application/json

{
    "image": "user-3.jpg"
}

###

DELETE http://localhost:8000/api/posts/4
